import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#b8feff] p-5">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto p-4 bg-[#a7dcdd] shadow-xl m-5 rounded-lg">
        {children}
        </div>
        </body>
    </html>
  );
}
